parser: y.tab.c lex.yy.c
	gcc -o parser y.tab.c
y.tab.c: CS315_F24_Team_28.y lex.yy.c
	yacc CS315_F24_Team_28.y
lex.yy.c: CS315_F24_Team_28.l
	lex CS315_F24_Team_28.l
clean:
	rm -f lex.yy.c y.tab.c parser
